package main

const DIGITS = "0123456789"
const LETTERS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
const LETTERS_DIGITS = LETTERS + DIGITS

const (
	TT_EOF = iota
	TT_ILLEGAL
	TT_FLOAT
	TT_INT
	TT_STRING
	TT_BOOL
	TT_PLUS
	TT_MINUS
	TT_MUL
	TT_DIV
	TT_POW
	TT_ASSIGN
	TT_LPAREN
	TT_RPAREN
	TT_LSQUARE
	TT_RSQUARE
)
