name: goreleaser

on:
    push:
        branches: [main]
        tags:
            - "*"

permissions:
    contents: write

jobs:
    goreleaser:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.16
            - name: Run GoReleaser
              uses: goreleaser/goreleaser-action@v4
              with:
                  distribution: goreleaser
                  version: 0.174.2
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
